spring:
  application:
    name: products-service
  config:
    import: configserver:http://root:s3cr3t@localhost:8888
  cloud:
    config:
      fail-fast: true

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/shop_products?serverTimezone=UTC
#    username: root
#    password:
#  application:
#    name: products-service
#  cloud:
#    config:
#      enabled: false

#server:
#  port: 8084

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
