spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ricardohuaripata/TodoCode-Curso-Microservicios.git
          searchPaths: tutorial-config-server/config-data

server:
  port: 8081
